# Dockerfile.dev

FROM node:20-alpine

# Enable Corepack and install pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /usr/src/app

# Install all dependencies including dev dependencies
COPY package*.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

# Copy all source code (with volume override in development, this step might be skipped)
COPY . .

#allow for listening on docker network, but don't expose to main server
EXPOSE 3000

# Use the Next.js development command
CMD ["pnpm", "run", "dev:frontend"]
