version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_dev
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db  # persists data locally (optional)
