version: "3.8"
services:
  mongo:
    image: mongo:latest # Change 'server:1.0.1' to official mongo image
    container_name: ${DATABASE_HOST}
    restart: always
    env_file: .env
    environment:
      #this will allow for direct connection to database vars via ENV file constraints
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${DATABASE_COLLECTION}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    networks:
      - app-net
    volumes:
      - database-v:/data/db
      - ./database/sslkey/security.keyFile:/etc/secrets/security.keyFile:rw
      - ./database/init-user.js:/docker-entrypoint-initdb.d/init-user.js:ro
    command: [ "mongod", "--replSet", "rs0", "--auth", "--keyFile", "/etc/secrets/security.keyFile" ]

  backend:
    image: server:1.0.0
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ${SERVER_HOST}
    depends_on:
      - mongo
    networks:
      - app-net
    env_file: .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./server:/server
      - server-v-node-modules:/server/node_modules

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: frontend
    depends_on:
      - backend
    networks:
      - app-net
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - ./:/usr/src/app

networks:
  app-net:
    driver: bridge

volumes:
  server-v-node-modules:
    name: "server-v-node-modules"
  database-v:
    name: "database-v"
