services:
  - type: web
    name: iot-pig-monitoring-frontend
    env: node
    buildCommand: npm install
    startCommand: npm run start
    plan: free
    branch: main
    autoDeploy: true
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: "https://iot-pig-monitoring-backend.onrender.com:3005"  # Backend URL for frontend communication
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        value: "pk_test_Z3VpZGVkLW9jdG9wdXMtMjEuY2xlcmsuYWNjb3VudHMuZGV2JA"
      - key: NEXT_PUBLIC_CLERK_SIGN_IN_URL
        value: "/sign-in"
      - key: NEXT_PUBLIC_CLERK_SIGN_UP_URL
        value: "/sign-up"
      - key: NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
        value: "/overview"
      - key: NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
        value: "/overview"

  - type: web
    name: iot-pig-monitoring-backend
    env: node
    buildCommand: npm install
    startCommand: npm run dev:backend
    plan: free
    branch: main
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        value: "mongodb+srv://test1:test@cluster0.zncmk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      - key: PORT
        value: "3005"  # Backend port
      - key: CLERK_SECRET_KEY
        value: "sk_test_jtL2mcRdMX0pfDedog8R96GuhWRtikw4D3pxm9wGE6"
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        value: "pk_test_Z3VpZGVkLW9jdG9wdXMtMjEuY2xlcmsuYWNjb3VudHMuZGV2JA"
      - key: NEXT_PUBLIC_CLERK_SIGN_IN_URL
        value: "/sign-in"
      - key: NEXT_PUBLIC_CLERK_SIGN_UP_URL
        value: "/sign-up"
      - key: NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
        value: "/overview"
      - key: NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
        value: "/overview"

  - type: database
    name: iot-pig-monitoring-db
    plan: free
    dbEngine: mongo
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        value: "mongodb+srv://test1:test@cluster0.zncmk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
    autoCreateDb: true
